insert into Employee (Job_title, Department, User_ID) values ('Computer Systems Analyst III', 4, 1);
insert into Employee (Job_title, Department, User_ID) values ('Sales Representative', 1, 2);
insert into Employee (Job_title, Department, User_ID) values ('Account Representative II', 1, 3);
insert into Employee (Job_title, Department, User_ID) values ('Analog Circuit Design manager', 4, 4);
insert into Employee (Job_title, Department, User_ID) values ('Accountant I', 5, 5);
insert into Employee (Job_title, Department, User_ID) values ('Research Assistant III', 1, 6);
insert into Employee (Job_title, Department, User_ID) values ('Pharmacist', 3, 7);
insert into Employee (Job_title, Department, User_ID) values ('Accountant III', 1, 8);
insert into Employee (Job_title, Department, User_ID) values ('Technical Writer', 5, 9);
insert into Employee (Job_title, Department, User_ID) values ('Social Worker', 1, 10);
insert into Employee (Job_title, Department, User_ID) values ('Software Engineer I', 2, 11);
insert into Employee (Job_title, Department, User_ID) values ('Teacher', 3, 12);
insert into Employee (Job_title, Department, User_ID) values ('Database Administrator III', 1, 13);
insert into Employee (Job_title, Department, User_ID) values ('Research Nurse', 1, 14);
insert into Employee (Job_title, Department, User_ID) values ('Research Assistant III', 3, 15);
insert into Employee (Job_title, Department, User_ID) values ('General Manager', 5, 16);
insert into Employee (Job_title, Department, User_ID) values ('Tax Accountant', 4, 17);
insert into Employee (Job_title, Department, User_ID) values ('VP Product Management', 5, 18);
insert into Employee (Job_title, Department, User_ID) values ('Occupational Therapist', 3, 19);
insert into Employee (Job_title, Department, User_ID) values ('Financial Analyst', 1, 20);
insert into Employee (Job_title, Department, User_ID) values ('Staff Accountant II', 2, 21);
insert into Employee (Job_title, Department, User_ID) values ('Physical Therapy Assistant', 4, 22);
insert into Employee (Job_title, Department, User_ID) values ('Dental Hygienist', 3, 23);
insert into Employee (Job_title, Department, User_ID) values ('Systems Administrator IV', 4, 24);
insert into Employee (Job_title, Department, User_ID) values ('Staff Scientist', 5, 25);
insert into Employee (Job_title, Department, User_ID) values ('Junior Executive', 1, 26);
insert into Employee (Job_title, Department, User_ID) values ('Marketing Assistant', 3, 27);
insert into Employee (Job_title, Department, User_ID) values ('Environmental Tech', 4, 28);
insert into Employee (Job_title, Department, User_ID) values ('Account Executive', 4, 29);
insert into Employee (Job_title, Department, User_ID) values ('Recruiter', 3, 30);
